/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_plugins_SidplayfpPlugin */

#ifndef _Included_com_ssb_droidsound_plugins_SidplayfpPlugin
#define _Included_com_ssb_droidsound_plugins_SidplayfpPlugin
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ssb_droidsound_plugins_SidplayfpPlugin
 * Method:    N_load
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_ssb_droidsound_plugins_SidplayfpPlugin_N_1load
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SidplayfpPlugin
 * Method:    N_unload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_SidplayfpPlugin_N_1unload
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ssb_droidsound_plugins_SidplayfpPlugin
 * Method:    N_getSoundData
 * Signature: (J[SI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_SidplayfpPlugin_N_1getSoundData
  (JNIEnv *, jobject, jlong, jshortArray, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SidplayfpPlugin
 * Method:    N_seekTo
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ssb_droidsound_plugins_SidplayfpPlugin_N_1seekTo
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SidplayfpPlugin
 * Method:    N_setTune
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ssb_droidsound_plugins_SidplayfpPlugin_N_1setTune
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SidplayfpPlugin
 * Method:    N_getStringInfo
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ssb_droidsound_plugins_SidplayfpPlugin_N_1getStringInfo
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SidplayfpPlugin
 * Method:    N_getIntInfo
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_SidplayfpPlugin_N_1getIntInfo
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SidplayfpPlugin
 * Method:    N_setOption
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_SidplayfpPlugin_N_1setOption
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
