/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_plugins_HTPlugin */

#ifndef _Included_com_ssb_droidsound_plugins_HTPlugin
#define _Included_com_ssb_droidsound_plugins_HTPlugin
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ssb_droidsound_plugins_HTPlugin_INFO_TITLE
#define com_ssb_droidsound_plugins_HTPlugin_INFO_TITLE 0L
#undef com_ssb_droidsound_plugins_HTPlugin_INFO_AUTHOR
#define com_ssb_droidsound_plugins_HTPlugin_INFO_AUTHOR 1L
#undef com_ssb_droidsound_plugins_HTPlugin_INFO_LENGTH
#define com_ssb_droidsound_plugins_HTPlugin_INFO_LENGTH 2L
#undef com_ssb_droidsound_plugins_HTPlugin_INFO_TYPE
#define com_ssb_droidsound_plugins_HTPlugin_INFO_TYPE 3L
#undef com_ssb_droidsound_plugins_HTPlugin_INFO_COPYRIGHT
#define com_ssb_droidsound_plugins_HTPlugin_INFO_COPYRIGHT 4L
#undef com_ssb_droidsound_plugins_HTPlugin_INFO_GAME
#define com_ssb_droidsound_plugins_HTPlugin_INFO_GAME 5L
#undef com_ssb_droidsound_plugins_HTPlugin_INFO_SUBTUNES
#define com_ssb_droidsound_plugins_HTPlugin_INFO_SUBTUNES 6L
#undef com_ssb_droidsound_plugins_HTPlugin_INFO_STARTTUNE
#define com_ssb_droidsound_plugins_HTPlugin_INFO_STARTTUNE 7L
#undef com_ssb_droidsound_plugins_HTPlugin_INFO_SUBTUNE_TITLE
#define com_ssb_droidsound_plugins_HTPlugin_INFO_SUBTUNE_TITLE 8L
#undef com_ssb_droidsound_plugins_HTPlugin_SIZEOF_INFO
#define com_ssb_droidsound_plugins_HTPlugin_SIZEOF_INFO 9L
#undef com_ssb_droidsound_plugins_HTPlugin_OPT_FILTER
#define com_ssb_droidsound_plugins_HTPlugin_OPT_FILTER 1L
#undef com_ssb_droidsound_plugins_HTPlugin_OPT_RESAMPLING
#define com_ssb_droidsound_plugins_HTPlugin_OPT_RESAMPLING 2L
#undef com_ssb_droidsound_plugins_HTPlugin_OPT_NTSC
#define com_ssb_droidsound_plugins_HTPlugin_OPT_NTSC 3L
#undef com_ssb_droidsound_plugins_HTPlugin_OPT_SPEED_HACK
#define com_ssb_droidsound_plugins_HTPlugin_OPT_SPEED_HACK 4L
/*
 * Class:     com_ssb_droidsound_plugins_HTPlugin
 * Method:    N_load
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ssb_droidsound_plugins_HTPlugin_N_1load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ssb_droidsound_plugins_HTPlugin
 * Method:    N_unload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_HTPlugin_N_1unload
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ssb_droidsound_plugins_HTPlugin
 * Method:    N_getSoundData
 * Signature: (J[SI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_HTPlugin_N_1getSoundData
  (JNIEnv *, jobject, jlong, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
