/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_plugins_HTPlugin */

#ifndef _Included_com_ssb_droidsound_plugins_HTPlugin
#define _Included_com_ssb_droidsound_plugins_HTPlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ssb_droidsound_plugins_HTPlugin
 * Method:    N_load
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ssb_droidsound_plugins_HTPlugin_N_1load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ssb_droidsound_plugins_HTPlugin
 * Method:    N_unload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_HTPlugin_N_1unload
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ssb_droidsound_plugins_HTPlugin
 * Method:    N_getSoundData
 * Signature: (J[SI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_HTPlugin_N_1getSoundData
  (JNIEnv *, jobject, jlong, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
